/**
 * Generated by Eclipse Mita 0.1.0.
 * @date 2019-05-16 00:16:33
 */


#ifndef MITA_TIME_H
#define MITA_TIME_H

#include <BCDS_Retcode.h>


Retcode_T SetupTime(void);

Retcode_T EnableTime(void);

Retcode_T EveryHandleEvery2Second1_Enable(void);


#endif
