/**
 * Generated by Eclipse Mita 0.1.0.
 * @date 2019-05-16 00:16:33
 */


#include <FreeRTOS.h>
#include <BCDS_Basics.h>
#include <BCDS_CmdProcessor.h>
#include <timers.h>
#include <BCDS_Retcode.h>
#include "MitaTime.h"
#include "MitaExceptions.h"
#include "MitaEvents.h"

static TimerHandle_t timerHandleEvery2Second1;

static void InternalHandleEvery2Second1(TimerHandle_t xTimer)
{
	BCDS_UNUSED(xTimer);
	CmdProcessor_Enqueue(&Mita_EventQueue, HandleEvery2Second1, NULL, 0);
}


Retcode_T SetupTime(void)
{
	
	timerHandleEvery2Second1 = xTimerCreate("timerHandleEvery2Second1", UINT32_C(2000), pdTRUE, NULL, InternalHandleEvery2Second1);
	
	if(timerHandleEvery2Second1 == NULL)
	{
		return RETCODE(RETCODE_SEVERITY_ERROR, RETCODE_OUT_OF_RESOURCES);
	}
	
	return NO_EXCEPTION;
}

Retcode_T EnableTime(void)
{
	Retcode_T result = NO_EXCEPTION;

	
	result = EveryHandleEvery2Second1_Enable();
	if(result != NO_EXCEPTION)
	{
		return result;
	}
	
	return NO_EXCEPTION;
}

Retcode_T EveryHandleEvery2Second1_Enable(void)
{
	xTimerStart(timerHandleEvery2Second1, 0);
	
	return NO_EXCEPTION;
}


