/**
 * Generated by Eclipse Mita 0.1.0.
 * @date 2019-05-16 00:16:33
 */


#include <inttypes.h>
#include <string.h>
#include <stdint.h>
#include <XdkSensorHandle.h>
#include <BCDS_Environmental.h>
#include <stdio.h>
#include <stdbool.h>
#include <BCDS_Basics.h>
#include <BCDS_Retcode.h>
#include "SensorEnvironment.h"
#include "MitaExceptions.h"
#include "application.h"

#ifndef BCDS_MODULE_ID
#define BCDS_MODULE_ID 0xCAFE
#endif


Retcode_T initGlobalVariables_application() {
	Retcode_T exception = RETCODE_OK;
	
	return exception;
}

Retcode_T HandleEveryButton_onePressed1(void* userParameter1, uint32_t userParameter2)
{
	
	BCDS_UNUSED(userParameter1);
	BCDS_UNUSED(userParameter2);

	Retcode_T exception = NO_EXCEPTION;
	
	
	printf("%s", "Hello World\n");


	return NO_EXCEPTION;
}

Retcode_T HandleEvery2Second1(void* userParameter1, uint32_t userParameter2)
{
	
	BCDS_UNUSED(userParameter1);
	BCDS_UNUSED(userParameter2);

	Retcode_T exception = NO_EXCEPTION;
	
	
	Environmental_Data_T sensorEnvironmentModalityPreparation_1;
	exception = Environmental_readData(xdkEnvironmental_BME280_Handle, &sensorEnvironmentModalityPreparation_1);
	if(exception != NO_EXCEPTION) return exception;
	
	uint32_t humidityValue;
	humidityValue = sensorEnvironmentModalityPreparation_1.humidity;
	int32_t temperature;
	temperature = sensorEnvironmentModalityPreparation_1.temperature;
	char message_buf[61] = {0};
	char *message = message_buf;
	
	char mainHandleEvery2Second12Message_4_buf[] = "Justin room sensors, Temp: ";
	memcpy(message, mainHandleEvery2Second12Message_4_buf, sizeof(mainHandleEvery2Second12Message_4_buf));
	
	char mainHandleEvery2Second12Message_1_buf[34] = {0};
	snprintf(mainHandleEvery2Second12Message_1_buf, sizeof(mainHandleEvery2Second12Message_1_buf), "%" PRId32 ", Humidity: %" PRIu32 "", temperature, humidityValue);
	strcat(message, mainHandleEvery2Second12Message_1_buf);
	printf("%s\n", message);


	return NO_EXCEPTION;
}


